/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsWingoRouteImport } from './routes/projects.wingo'
import { Route as ProjectsVenaRouteImport } from './routes/projects.vena'
import { Route as ProjectsProjectsQuestRouteImport } from './routes/projects.projects-quest'
import { Route as ProjectsLumosRouteImport } from './routes/projects.lumos'
import { Route as ProjectsKridaRouteImport } from './routes/projects.krida'
import { Route as ProjectsExhibitionDisplayRouteImport } from './routes/projects.exhibition-display'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsWingoRoute = ProjectsWingoRouteImport.update({
  id: '/projects/wingo',
  path: '/projects/wingo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsVenaRoute = ProjectsVenaRouteImport.update({
  id: '/projects/vena',
  path: '/projects/vena',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectsQuestRoute = ProjectsProjectsQuestRouteImport.update({
  id: '/projects/projects-quest',
  path: '/projects/projects-quest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsLumosRoute = ProjectsLumosRouteImport.update({
  id: '/projects/lumos',
  path: '/projects/lumos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsKridaRoute = ProjectsKridaRouteImport.update({
  id: '/projects/krida',
  path: '/projects/krida',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsExhibitionDisplayRoute =
  ProjectsExhibitionDisplayRouteImport.update({
    id: '/projects/exhibition-display',
    path: '/projects/exhibition-display',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/exhibition-display': typeof ProjectsExhibitionDisplayRoute
  '/projects/krida': typeof ProjectsKridaRoute
  '/projects/lumos': typeof ProjectsLumosRoute
  '/projects/projects-quest': typeof ProjectsProjectsQuestRoute
  '/projects/vena': typeof ProjectsVenaRoute
  '/projects/wingo': typeof ProjectsWingoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/exhibition-display': typeof ProjectsExhibitionDisplayRoute
  '/projects/krida': typeof ProjectsKridaRoute
  '/projects/lumos': typeof ProjectsLumosRoute
  '/projects/projects-quest': typeof ProjectsProjectsQuestRoute
  '/projects/vena': typeof ProjectsVenaRoute
  '/projects/wingo': typeof ProjectsWingoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/exhibition-display': typeof ProjectsExhibitionDisplayRoute
  '/projects/krida': typeof ProjectsKridaRoute
  '/projects/lumos': typeof ProjectsLumosRoute
  '/projects/projects-quest': typeof ProjectsProjectsQuestRoute
  '/projects/vena': typeof ProjectsVenaRoute
  '/projects/wingo': typeof ProjectsWingoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/projects/$slug'
    | '/projects/exhibition-display'
    | '/projects/krida'
    | '/projects/lumos'
    | '/projects/projects-quest'
    | '/projects/vena'
    | '/projects/wingo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/projects/$slug'
    | '/projects/exhibition-display'
    | '/projects/krida'
    | '/projects/lumos'
    | '/projects/projects-quest'
    | '/projects/vena'
    | '/projects/wingo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/projects/$slug'
    | '/projects/exhibition-display'
    | '/projects/krida'
    | '/projects/lumos'
    | '/projects/projects-quest'
    | '/projects/vena'
    | '/projects/wingo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsExhibitionDisplayRoute: typeof ProjectsExhibitionDisplayRoute
  ProjectsKridaRoute: typeof ProjectsKridaRoute
  ProjectsLumosRoute: typeof ProjectsLumosRoute
  ProjectsProjectsQuestRoute: typeof ProjectsProjectsQuestRoute
  ProjectsVenaRoute: typeof ProjectsVenaRoute
  ProjectsWingoRoute: typeof ProjectsWingoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/wingo': {
      id: '/projects/wingo'
      path: '/projects/wingo'
      fullPath: '/projects/wingo'
      preLoaderRoute: typeof ProjectsWingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/vena': {
      id: '/projects/vena'
      path: '/projects/vena'
      fullPath: '/projects/vena'
      preLoaderRoute: typeof ProjectsVenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/projects-quest': {
      id: '/projects/projects-quest'
      path: '/projects/projects-quest'
      fullPath: '/projects/projects-quest'
      preLoaderRoute: typeof ProjectsProjectsQuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/lumos': {
      id: '/projects/lumos'
      path: '/projects/lumos'
      fullPath: '/projects/lumos'
      preLoaderRoute: typeof ProjectsLumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/krida': {
      id: '/projects/krida'
      path: '/projects/krida'
      fullPath: '/projects/krida'
      preLoaderRoute: typeof ProjectsKridaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/exhibition-display': {
      id: '/projects/exhibition-display'
      path: '/projects/exhibition-display'
      fullPath: '/projects/exhibition-display'
      preLoaderRoute: typeof ProjectsExhibitionDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsExhibitionDisplayRoute: ProjectsExhibitionDisplayRoute,
  ProjectsKridaRoute: ProjectsKridaRoute,
  ProjectsLumosRoute: ProjectsLumosRoute,
  ProjectsProjectsQuestRoute: ProjectsProjectsQuestRoute,
  ProjectsVenaRoute: ProjectsVenaRoute,
  ProjectsWingoRoute: ProjectsWingoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
